// Generated by packages/m3e/scripts/build-registry.mjs (bun run registry:build). Do not edit.
export type RegistryMeta = {
  title: string
  type: string
  /** npm packages */
  dependencies: string[]
  /** other items of this registry */
  registryDependencies: string[]
  /** Material Symbols the item uses; glyph is an Iconify name that is bundled */
  icons: { name: string; glyph: string }[]
  files: { path: string; target: string }[]
}

export const REGISTRY_META: Record<string, RegistryMeta> = {
  "styles": {
    "title": "M3E styles",
    "type": "registry:file",
    "dependencies": [
      "@fontsource-variable/jetbrains-mono",
      "@fontsource-variable/roboto-flex",
      "shadcn",
      "tw-animate-css"
    ],
    "registryDependencies": [],
    "icons": [],
    "files": [
      {
        "path": "src/styles/m3e.css",
        "target": "@lib/m3e/m3e.css"
      },
      {
        "path": "src/styles/m3e.generated.css",
        "target": "@lib/m3e/m3e.generated.css"
      }
    ]
  },
  "cn": {
    "title": "cn",
    "type": "registry:lib",
    "dependencies": [
      "cn"
    ],
    "registryDependencies": [],
    "icons": [],
    "files": [
      {
        "path": "src/lib/m3e/cn.ts",
        "target": "@lib/m3e/cn.ts"
      }
    ]
  },
  "shapes": {
    "title": "Shapes",
    "type": "registry:lib",
    "dependencies": [],
    "registryDependencies": [],
    "icons": [],
    "files": [
      {
        "path": "src/lib/m3e/shapes.ts",
        "target": "@lib/m3e/shapes.ts"
      }
    ]
  },
  "shape": {
    "title": "Shape",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/shape.tsx",
        "target": "@components/m3e/shape.tsx"
      },
      {
        "path": "src/lib/m3e/shape-library.ts",
        "target": "@lib/m3e/shape-library.ts"
      }
    ]
  },
  "icon": {
    "title": "Icon",
    "type": "registry:ui",
    "dependencies": [
      "@iconify/react"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_downward",
        "glyph": "arrow-downward-rounded"
      },
      {
        "name": "arrow_drop_down",
        "glyph": "arrow-drop-down-rounded"
      },
      {
        "name": "cancel",
        "glyph": "cancel-outline-rounded"
      },
      {
        "name": "check",
        "glyph": "check-rounded"
      },
      {
        "name": "check_circle",
        "glyph": "check-circle-outline-rounded"
      },
      {
        "name": "chevron_left",
        "glyph": "chevron-left-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      },
      {
        "name": "close",
        "glyph": "close-rounded"
      },
      {
        "name": "info",
        "glyph": "info-outline-rounded"
      },
      {
        "name": "keyboard_arrow_down",
        "glyph": "keyboard-arrow-down-rounded"
      },
      {
        "name": "keyboard_arrow_up",
        "glyph": "keyboard-arrow-up-rounded"
      },
      {
        "name": "menu",
        "glyph": "menu-rounded"
      },
      {
        "name": "more_horiz",
        "glyph": "more-horiz"
      },
      {
        "name": "progress_activity",
        "glyph": "progress-activity"
      },
      {
        "name": "remove",
        "glyph": "remove-rounded"
      },
      {
        "name": "search",
        "glyph": "search-rounded"
      },
      {
        "name": "warning",
        "glyph": "warning-outline-rounded"
      },
      {
        "name": "x",
        "glyph": "x-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/icon.tsx",
        "target": "@components/m3e/icon.tsx"
      },
      {
        "path": "src/components/m3e/icon-registry.ts",
        "target": "@components/m3e/icon-registry.ts"
      },
      {
        "path": "src/components/m3e/icon-data.ts",
        "target": "@components/m3e/icon-data.ts"
      },
      {
        "path": "src/components/m3e/icon-data.app.ts",
        "target": "@components/m3e/icon-data.app.ts"
      },
      {
        "path": "src/components/m3e/symbols.tsx",
        "target": "@components/m3e/symbols.tsx"
      },
      {
        "path": "scripts/icons.mjs",
        "target": "~/scripts/icons.mjs"
      }
    ]
  },
  "theme": {
    "title": "Theme provider",
    "type": "registry:ui",
    "dependencies": [
      "@material/material-color-utilities"
    ],
    "registryDependencies": [
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/m3e-provider.tsx",
        "target": "@components/m3e/m3e-provider.tsx"
      },
      {
        "path": "src/components/m3e/color-mode-provider.tsx",
        "target": "@components/m3e/color-mode-provider.tsx"
      },
      {
        "path": "src/components/m3e/m3-theme-provider.tsx",
        "target": "@components/m3e/m3-theme-provider.tsx"
      },
      {
        "path": "src/components/m3e/m3-theme-scope.tsx",
        "target": "@components/m3e/m3-theme-scope.tsx"
      },
      {
        "path": "src/lib/m3e/color.ts",
        "target": "@lib/m3e/color.ts"
      },
      {
        "path": "src/lib/m3e/baseline.ts",
        "target": "@lib/m3e/baseline.ts"
      }
    ]
  },
  "use-mobile": {
    "title": "useIsMobile",
    "type": "registry:hook",
    "dependencies": [],
    "registryDependencies": [],
    "icons": [],
    "files": [
      {
        "path": "src/hooks/use-mobile.ts",
        "target": "@hooks/use-mobile.ts"
      }
    ]
  },
  "use-image-theme": {
    "title": "Theme from an image",
    "type": "registry:hook",
    "dependencies": [
      "@material/material-color-utilities",
      "node-vibrant"
    ],
    "registryDependencies": [
      "theme"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/use-image-theme.ts",
        "target": "@components/m3e/use-image-theme.ts"
      },
      {
        "path": "src/lib/m3e/vibrant.ts",
        "target": "@lib/m3e/vibrant.ts"
      }
    ]
  },
  "accordion": {
    "title": "Accordion",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "keyboard_arrow_down",
        "glyph": "keyboard-arrow-down-rounded"
      },
      {
        "name": "keyboard_arrow_up",
        "glyph": "keyboard-arrow-up-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/accordion.tsx",
        "target": "@components/m3e/accordion.tsx"
      }
    ]
  },
  "alert-dialog": {
    "title": "Alert Dialog",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "portal-container",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/alert-dialog.tsx",
        "target": "@components/m3e/alert-dialog.tsx"
      }
    ]
  },
  "alert": {
    "title": "Alert",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/alert.tsx",
        "target": "@components/m3e/alert.tsx"
      }
    ]
  },
  "app-bar": {
    "title": "App Bar",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/app-bar.tsx",
        "target": "@components/m3e/app-bar.tsx"
      }
    ]
  },
  "aspect-ratio": {
    "title": "Aspect Ratio",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/aspect-ratio.tsx",
        "target": "@components/m3e/aspect-ratio.tsx"
      }
    ]
  },
  "attachment": {
    "title": "Attachment",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/attachment.tsx",
        "target": "@components/m3e/attachment.tsx"
      }
    ]
  },
  "avatar": {
    "title": "Avatar",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/avatar.tsx",
        "target": "@components/m3e/avatar.tsx"
      }
    ]
  },
  "badge": {
    "title": "Badge",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/badge.tsx",
        "target": "@components/m3e/badge.tsx"
      }
    ]
  },
  "breadcrumb": {
    "title": "Breadcrumb",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      },
      {
        "name": "more_horiz",
        "glyph": "more-horiz"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/breadcrumb.tsx",
        "target": "@components/m3e/breadcrumb.tsx"
      }
    ]
  },
  "bubble": {
    "title": "Bubble",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/bubble.tsx",
        "target": "@components/m3e/bubble.tsx"
      }
    ]
  },
  "button-group": {
    "title": "Button Group",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "separator",
      "styles",
      "use-standard-group"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/button-group.tsx",
        "target": "@components/m3e/button-group.tsx"
      }
    ]
  },
  "button": {
    "title": "Button",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/button.tsx",
        "target": "@components/m3e/button.tsx"
      }
    ]
  },
  "calendar": {
    "title": "Calendar",
    "type": "registry:ui",
    "dependencies": [
      "react-day-picker"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_drop_down",
        "glyph": "arrow-drop-down-rounded"
      },
      {
        "name": "chevron_left",
        "glyph": "chevron-left-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/calendar.tsx",
        "target": "@components/m3e/calendar.tsx"
      }
    ]
  },
  "card": {
    "title": "Card",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/card.tsx",
        "target": "@components/m3e/card.tsx"
      }
    ]
  },
  "carousel": {
    "title": "Carousel",
    "type": "registry:ui",
    "dependencies": [
      "embla-carousel-react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "chevron_left",
        "glyph": "chevron-left-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/carousel.tsx",
        "target": "@components/m3e/carousel.tsx"
      }
    ]
  },
  "chart": {
    "title": "Chart",
    "type": "registry:ui",
    "dependencies": [
      "recharts@3.8.0"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/chart.tsx",
        "target": "@components/m3e/chart.tsx"
      }
    ]
  },
  "checkbox": {
    "title": "Checkbox",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/checkbox.tsx",
        "target": "@components/m3e/checkbox.tsx"
      }
    ]
  },
  "chip": {
    "title": "Chip",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-outline-rounded"
      },
      {
        "name": "close",
        "glyph": "close-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/chip.tsx",
        "target": "@components/m3e/chip.tsx"
      }
    ]
  },
  "circular-progress": {
    "title": "Circular Progress",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/circular-progress.tsx",
        "target": "@components/m3e/circular-progress.tsx"
      }
    ]
  },
  "collapsible": {
    "title": "Collapsible",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/collapsible.tsx",
        "target": "@components/m3e/collapsible.tsx"
      }
    ]
  },
  "combobox": {
    "title": "Combobox",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "input-group",
      "portal-container",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-rounded"
      },
      {
        "name": "close",
        "glyph": "close-rounded"
      },
      {
        "name": "keyboard_arrow_down",
        "glyph": "keyboard-arrow-down-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/combobox.tsx",
        "target": "@components/m3e/combobox.tsx"
      }
    ]
  },
  "command": {
    "title": "Command",
    "type": "registry:ui",
    "dependencies": [
      "cmdk"
    ],
    "registryDependencies": [
      "cn",
      "dialog",
      "icon",
      "input-group",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-rounded"
      },
      {
        "name": "search",
        "glyph": "search-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/command.tsx",
        "target": "@components/m3e/command.tsx"
      }
    ]
  },
  "context-menu": {
    "title": "Context Menu",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "portal-container",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/context-menu.tsx",
        "target": "@components/m3e/context-menu.tsx"
      }
    ]
  },
  "date-picker": {
    "title": "Date Picker",
    "type": "registry:ui",
    "dependencies": [
      "react-day-picker"
    ],
    "registryDependencies": [
      "button",
      "calendar",
      "cn",
      "dialog",
      "icon",
      "popover",
      "scroll-area",
      "styles",
      "text-field"
    ],
    "icons": [
      {
        "name": "arrow_drop_down",
        "glyph": "arrow-drop-down-outline-rounded"
      },
      {
        "name": "calendar_today",
        "glyph": "calendar-today-outline-rounded"
      },
      {
        "name": "chevron_left",
        "glyph": "chevron-left-outline-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-outline-rounded"
      },
      {
        "name": "edit",
        "glyph": "edit-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/date-picker.tsx",
        "target": "@components/m3e/date-picker.tsx"
      }
    ]
  },
  "dialog": {
    "title": "Dialog",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "portal-container",
      "styles"
    ],
    "icons": [
      {
        "name": "close",
        "glyph": "close-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/dialog.tsx",
        "target": "@components/m3e/dialog.tsx"
      }
    ]
  },
  "drawer": {
    "title": "Drawer",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "portal-container",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/drawer.tsx",
        "target": "@components/m3e/drawer.tsx"
      }
    ]
  },
  "dropdown-menu": {
    "title": "Dropdown Menu",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "portal-container",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/dropdown-menu.tsx",
        "target": "@components/m3e/dropdown-menu.tsx"
      }
    ]
  },
  "empty": {
    "title": "Empty",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/empty.tsx",
        "target": "@components/m3e/empty.tsx"
      }
    ]
  },
  "expressive-carousel": {
    "title": "Expressive Carousel",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/expressive-carousel.tsx",
        "target": "@components/m3e/expressive-carousel.tsx"
      }
    ]
  },
  "fab-menu": {
    "title": "Fab Menu",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "fab",
      "icon",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "add",
        "glyph": "add-outline-rounded"
      },
      {
        "name": "close",
        "glyph": "close-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/fab-menu.tsx",
        "target": "@components/m3e/fab-menu.tsx"
      }
    ]
  },
  "fab": {
    "title": "Fab",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/fab.tsx",
        "target": "@components/m3e/fab.tsx"
      }
    ]
  },
  "field": {
    "title": "Field",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "label",
      "separator",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/field.tsx",
        "target": "@components/m3e/field.tsx"
      }
    ]
  },
  "hover-card": {
    "title": "Hover Card",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "portal-container",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/hover-card.tsx",
        "target": "@components/m3e/hover-card.tsx"
      }
    ]
  },
  "input-group": {
    "title": "Input Group",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "input",
      "styles",
      "textarea"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/input-group.tsx",
        "target": "@components/m3e/input-group.tsx"
      }
    ]
  },
  "input-otp": {
    "title": "Input Otp",
    "type": "registry:ui",
    "dependencies": [
      "input-otp"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "remove",
        "glyph": "remove-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/input-otp.tsx",
        "target": "@components/m3e/input-otp.tsx"
      }
    ]
  },
  "input": {
    "title": "Input",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/input.tsx",
        "target": "@components/m3e/input.tsx"
      }
    ]
  },
  "item": {
    "title": "Item",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "separator",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/item.tsx",
        "target": "@components/m3e/item.tsx"
      }
    ]
  },
  "kbd": {
    "title": "Kbd",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/kbd.tsx",
        "target": "@components/m3e/kbd.tsx"
      }
    ]
  },
  "label": {
    "title": "Label",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/label.tsx",
        "target": "@components/m3e/label.tsx"
      }
    ]
  },
  "loading-indicator": {
    "title": "Loading Indicator",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "shapes",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/loading-indicator.tsx",
        "target": "@components/m3e/loading-indicator.tsx"
      }
    ]
  },
  "marker": {
    "title": "Marker",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/marker.tsx",
        "target": "@components/m3e/marker.tsx"
      }
    ]
  },
  "menubar": {
    "title": "Menubar",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "dropdown-menu",
      "icon",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/menubar.tsx",
        "target": "@components/m3e/menubar.tsx"
      }
    ]
  },
  "message-scroller": {
    "title": "Message Scroller",
    "type": "registry:ui",
    "dependencies": [
      "@shadcn/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_downward",
        "glyph": "arrow-downward-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/message-scroller.tsx",
        "target": "@components/m3e/message-scroller.tsx"
      }
    ]
  },
  "message": {
    "title": "Message",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/message.tsx",
        "target": "@components/m3e/message.tsx"
      }
    ]
  },
  "native-select": {
    "title": "Native Select",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_drop_down",
        "glyph": "arrow-drop-down-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/native-select.tsx",
        "target": "@components/m3e/native-select.tsx"
      }
    ]
  },
  "navigation-menu": {
    "title": "Navigation Menu",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "portal-container",
      "styles"
    ],
    "icons": [
      {
        "name": "keyboard_arrow_down",
        "glyph": "keyboard-arrow-down-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/navigation-menu.tsx",
        "target": "@components/m3e/navigation-menu.tsx"
      }
    ]
  },
  "navigation": {
    "title": "Navigation",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "badge",
      "cn",
      "icon",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/navigation.tsx",
        "target": "@components/m3e/navigation.tsx"
      }
    ]
  },
  "pagination": {
    "title": "Pagination",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "chevron_left",
        "glyph": "chevron-left-rounded"
      },
      {
        "name": "chevron_right",
        "glyph": "chevron-right-rounded"
      },
      {
        "name": "more_horiz",
        "glyph": "more-horiz"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/pagination.tsx",
        "target": "@components/m3e/pagination.tsx"
      }
    ]
  },
  "popover": {
    "title": "Popover",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "portal-container",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/popover.tsx",
        "target": "@components/m3e/popover.tsx"
      }
    ]
  },
  "portal-container": {
    "title": "Portal Container",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/portal-container.tsx",
        "target": "@components/m3e/portal-container.tsx"
      }
    ]
  },
  "progress": {
    "title": "Progress",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/progress.tsx",
        "target": "@components/m3e/progress.tsx"
      }
    ]
  },
  "questionnaire": {
    "title": "Questionnaire",
    "type": "registry:ui",
    "dependencies": [
      "@shadcn/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "check",
        "glyph": "check-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/questionnaire.tsx",
        "target": "@components/m3e/questionnaire.tsx"
      }
    ]
  },
  "radio-group": {
    "title": "Radio Group",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/radio-group.tsx",
        "target": "@components/m3e/radio-group.tsx"
      }
    ]
  },
  "resizable": {
    "title": "Resizable",
    "type": "registry:ui",
    "dependencies": [
      "react-resizable-panels"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/resizable.tsx",
        "target": "@components/m3e/resizable.tsx"
      }
    ]
  },
  "ripple": {
    "title": "Ripple",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/ripple.tsx",
        "target": "@components/m3e/ripple.tsx"
      }
    ]
  },
  "scroll-area": {
    "title": "Scroll Area",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/scroll-area.tsx",
        "target": "@components/m3e/scroll-area.tsx"
      }
    ]
  },
  "search": {
    "title": "Search",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_back",
        "glyph": "arrow-back-outline-rounded"
      },
      {
        "name": "close",
        "glyph": "close-outline-rounded"
      },
      {
        "name": "search",
        "glyph": "search-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/search.tsx",
        "target": "@components/m3e/search.tsx"
      }
    ]
  },
  "select": {
    "title": "Select",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "icon",
      "portal-container",
      "ripple",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_drop_down",
        "glyph": "arrow-drop-down-rounded"
      },
      {
        "name": "check",
        "glyph": "check-rounded"
      },
      {
        "name": "keyboard_arrow_down",
        "glyph": "keyboard-arrow-down-rounded"
      },
      {
        "name": "keyboard_arrow_up",
        "glyph": "keyboard-arrow-up-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/select.tsx",
        "target": "@components/m3e/select.tsx"
      }
    ]
  },
  "separator": {
    "title": "Separator",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/separator.tsx",
        "target": "@components/m3e/separator.tsx"
      }
    ]
  },
  "sheet": {
    "title": "Sheet",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "portal-container",
      "styles"
    ],
    "icons": [
      {
        "name": "close",
        "glyph": "close-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/sheet.tsx",
        "target": "@components/m3e/sheet.tsx"
      }
    ]
  },
  "side-sheet": {
    "title": "Side Sheet",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "scroll-area",
      "styles"
    ],
    "icons": [
      {
        "name": "arrow_back",
        "glyph": "arrow-back-outline-rounded"
      },
      {
        "name": "close",
        "glyph": "close-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/side-sheet.tsx",
        "target": "@components/m3e/side-sheet.tsx"
      }
    ]
  },
  "sidebar": {
    "title": "Sidebar",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "input",
      "separator",
      "sheet",
      "skeleton",
      "styles",
      "tooltip",
      "use-mobile"
    ],
    "icons": [
      {
        "name": "menu",
        "glyph": "menu-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/sidebar.tsx",
        "target": "@components/m3e/sidebar.tsx"
      }
    ]
  },
  "skeleton": {
    "title": "Skeleton",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/skeleton.tsx",
        "target": "@components/m3e/skeleton.tsx"
      }
    ]
  },
  "slider": {
    "title": "Slider",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/slider.tsx",
        "target": "@components/m3e/slider.tsx"
      }
    ]
  },
  "sonner": {
    "title": "Sonner",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "portal-container",
      "styles"
    ],
    "icons": [
      {
        "name": "close",
        "glyph": "close-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/sonner.tsx",
        "target": "@components/m3e/sonner.tsx"
      }
    ]
  },
  "spinner": {
    "title": "Spinner",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/spinner.tsx",
        "target": "@components/m3e/spinner.tsx"
      }
    ]
  },
  "split-button": {
    "title": "Split Button",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "keyboard_arrow_down",
        "glyph": "keyboard-arrow-down-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/split-button.tsx",
        "target": "@components/m3e/split-button.tsx"
      }
    ]
  },
  "switch": {
    "title": "Switch",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/switch.tsx",
        "target": "@components/m3e/switch.tsx"
      }
    ]
  },
  "table": {
    "title": "Table",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/table.tsx",
        "target": "@components/m3e/table.tsx"
      }
    ]
  },
  "tabs": {
    "title": "Tabs",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/tabs.tsx",
        "target": "@components/m3e/tabs.tsx"
      }
    ]
  },
  "text-field": {
    "title": "Text Field",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/text-field.tsx",
        "target": "@components/m3e/text-field.tsx"
      }
    ]
  },
  "textarea": {
    "title": "Textarea",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "input",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/textarea.tsx",
        "target": "@components/m3e/textarea.tsx"
      }
    ]
  },
  "time-picker": {
    "title": "Time Picker",
    "type": "registry:ui",
    "dependencies": [],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "styles"
    ],
    "icons": [
      {
        "name": "keyboard",
        "glyph": "keyboard-outline-rounded"
      },
      {
        "name": "schedule",
        "glyph": "schedule-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/time-picker.tsx",
        "target": "@components/m3e/time-picker.tsx"
      }
    ]
  },
  "toast": {
    "title": "Toast",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "button",
      "cn",
      "icon",
      "portal-container",
      "styles"
    ],
    "icons": [
      {
        "name": "cancel",
        "glyph": "cancel-outline-rounded"
      },
      {
        "name": "check_circle",
        "glyph": "check-circle-outline-rounded"
      },
      {
        "name": "close",
        "glyph": "close-rounded"
      },
      {
        "name": "info",
        "glyph": "info-outline-rounded"
      },
      {
        "name": "progress_activity",
        "glyph": "progress-activity"
      },
      {
        "name": "warning",
        "glyph": "warning-outline-rounded"
      }
    ],
    "files": [
      {
        "path": "src/components/m3e/toast.tsx",
        "target": "@components/m3e/toast.tsx"
      }
    ]
  },
  "toggle-group": {
    "title": "Toggle Group",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles",
      "toggle",
      "use-standard-group"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/toggle-group.tsx",
        "target": "@components/m3e/toggle-group.tsx"
      }
    ]
  },
  "toggle": {
    "title": "Toggle",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react",
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "ripple",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/toggle.tsx",
        "target": "@components/m3e/toggle.tsx"
      }
    ]
  },
  "toolbar": {
    "title": "Toolbar",
    "type": "registry:ui",
    "dependencies": [
      "class-variance-authority"
    ],
    "registryDependencies": [
      "cn",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/toolbar.tsx",
        "target": "@components/m3e/toolbar.tsx"
      }
    ]
  },
  "tooltip": {
    "title": "Tooltip",
    "type": "registry:ui",
    "dependencies": [
      "@base-ui/react"
    ],
    "registryDependencies": [
      "cn",
      "portal-container",
      "styles"
    ],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/tooltip.tsx",
        "target": "@components/m3e/tooltip.tsx"
      }
    ]
  },
  "use-standard-group": {
    "title": "Use Standard Group",
    "type": "registry:hook",
    "dependencies": [],
    "registryDependencies": [],
    "icons": [],
    "files": [
      {
        "path": "src/components/m3e/use-standard-group.ts",
        "target": "@components/m3e/use-standard-group.ts"
      }
    ]
  },
  "base": {
    "title": "M3E base",
    "type": "registry:lib",
    "dependencies": [],
    "registryDependencies": [
      "styles",
      "cn",
      "theme",
      "icon"
    ],
    "icons": [],
    "files": []
  },
  "all": {
    "title": "All of M3E",
    "type": "registry:lib",
    "dependencies": [],
    "registryDependencies": [
      "accordion",
      "alert",
      "alert-dialog",
      "app-bar",
      "aspect-ratio",
      "attachment",
      "avatar",
      "badge",
      "base",
      "breadcrumb",
      "bubble",
      "button",
      "button-group",
      "calendar",
      "card",
      "carousel",
      "chart",
      "checkbox",
      "chip",
      "circular-progress",
      "collapsible",
      "combobox",
      "command",
      "context-menu",
      "date-picker",
      "dialog",
      "drawer",
      "dropdown-menu",
      "empty",
      "expressive-carousel",
      "fab",
      "fab-menu",
      "field",
      "hover-card",
      "icon",
      "input",
      "input-group",
      "input-otp",
      "item",
      "kbd",
      "label",
      "loading-indicator",
      "marker",
      "menubar",
      "message",
      "message-scroller",
      "native-select",
      "navigation",
      "navigation-menu",
      "pagination",
      "popover",
      "portal-container",
      "progress",
      "questionnaire",
      "radio-group",
      "resizable",
      "ripple",
      "scroll-area",
      "search",
      "select",
      "separator",
      "shape",
      "sheet",
      "side-sheet",
      "sidebar",
      "skeleton",
      "slider",
      "sonner",
      "spinner",
      "split-button",
      "switch",
      "table",
      "tabs",
      "text-field",
      "textarea",
      "theme",
      "time-picker",
      "toast",
      "toggle",
      "toggle-group",
      "toolbar",
      "tooltip"
    ],
    "icons": [],
    "files": []
  }
}
