// Generated by scripts/gen-parts-components.mjs (bun run gen:parts). Do not edit.
import * as m_accordion from "@/components/m3e/accordion";
import * as m_alert from "@/components/m3e/alert";
import * as m_alertDialog from "@/components/m3e/alert-dialog";
import * as m_appBar from "@/components/m3e/app-bar";
import * as m_aspectRatio from "@/components/m3e/aspect-ratio";
import * as m_attachment from "@/components/m3e/attachment";
import * as m_avatar from "@/components/m3e/avatar";
import * as m_badge from "@/components/m3e/badge";
import * as m_breadcrumb from "@/components/m3e/breadcrumb";
import * as m_bubble from "@/components/m3e/bubble";
import * as m_button from "@/components/m3e/button";
import * as m_buttonGroup from "@/components/m3e/button-group";
import * as m_calendar from "@/components/m3e/calendar";
import * as m_card from "@/components/m3e/card";
import * as m_carousel from "@/components/m3e/carousel";
import * as m_chart from "@/components/m3e/chart";
import * as m_checkbox from "@/components/m3e/checkbox";
import * as m_chip from "@/components/m3e/chip";
import * as m_circularProgress from "@/components/m3e/circular-progress";
import * as m_collapsible from "@/components/m3e/collapsible";
import * as m_combobox from "@/components/m3e/combobox";
import * as m_command from "@/components/m3e/command";
import * as m_contextMenu from "@/components/m3e/context-menu";
import * as m_datePicker from "@/components/m3e/date-picker";
import * as m_dialog from "@/components/m3e/dialog";
import * as m_drawer from "@/components/m3e/drawer";
import * as m_dropdownMenu from "@/components/m3e/dropdown-menu";
import * as m_empty from "@/components/m3e/empty";
import * as m_expressiveCarousel from "@/components/m3e/expressive-carousel";
import * as m_fab from "@/components/m3e/fab";
import * as m_fabMenu from "@/components/m3e/fab-menu";
import * as m_field from "@/components/m3e/field";
import * as m_hoverCard from "@/components/m3e/hover-card";
import * as m_icon from "@/components/m3e/icon";
import * as m_input from "@/components/m3e/input";
import * as m_inputGroup from "@/components/m3e/input-group";
import * as m_inputOtp from "@/components/m3e/input-otp";
import * as m_item from "@/components/m3e/item";
import * as m_kbd from "@/components/m3e/kbd";
import * as m_label from "@/components/m3e/label";
import * as m_loadingIndicator from "@/components/m3e/loading-indicator";
import * as m_m3ThemeScope from "@/components/m3e/m3-theme-scope";
import * as m_marker from "@/components/m3e/marker";
import * as m_menubar from "@/components/m3e/menubar";
import * as m_message from "@/components/m3e/message";
import * as m_messageScroller from "@/components/m3e/message-scroller";
import * as m_nativeSelect from "@/components/m3e/native-select";
import * as m_navigation from "@/components/m3e/navigation";
import * as m_navigationMenu from "@/components/m3e/navigation-menu";
import * as m_pagination from "@/components/m3e/pagination";
import * as m_popover from "@/components/m3e/popover";
import * as m_portalContainer from "@/components/m3e/portal-container";
import * as m_progress from "@/components/m3e/progress";
import * as m_questionnaire from "@/components/m3e/questionnaire";
import * as m_radioGroup from "@/components/m3e/radio-group";
import * as m_resizable from "@/components/m3e/resizable";
import * as m_scrollArea from "@/components/m3e/scroll-area";
import * as m_search from "@/components/m3e/search";
import * as m_select from "@/components/m3e/select";
import * as m_separator from "@/components/m3e/separator";
import * as m_shape from "@/components/m3e/shape";
import * as m_sheet from "@/components/m3e/sheet";
import * as m_sideSheet from "@/components/m3e/side-sheet";
import * as m_sidebar from "@/components/m3e/sidebar";
import * as m_skeleton from "@/components/m3e/skeleton";
import * as m_slider from "@/components/m3e/slider";
import * as m_sonner from "@/components/m3e/sonner";
import * as m_spinner from "@/components/m3e/spinner";
import * as m_splitButton from "@/components/m3e/split-button";
import * as m_switch from "@/components/m3e/switch";
import * as m_table from "@/components/m3e/table";
import * as m_tabs from "@/components/m3e/tabs";
import * as m_textField from "@/components/m3e/text-field";
import * as m_textarea from "@/components/m3e/textarea";
import * as m_timePicker from "@/components/m3e/time-picker";
import * as m_toast from "@/components/m3e/toast";
import * as m_toggle from "@/components/m3e/toggle";
import * as m_toggleGroup from "@/components/m3e/toggle-group";
import * as m_toolbar from "@/components/m3e/toolbar";
import * as m_tooltip from "@/components/m3e/tooltip";

/** every shadcn M3E module a part may use, by its file name (also its registry item name) */
export const MODULES: Record<string, Record<string, unknown>> = {
  "accordion": m_accordion,
  "alert": m_alert,
  "alert-dialog": m_alertDialog,
  "app-bar": m_appBar,
  "aspect-ratio": m_aspectRatio,
  "attachment": m_attachment,
  "avatar": m_avatar,
  "badge": m_badge,
  "breadcrumb": m_breadcrumb,
  "bubble": m_bubble,
  "button": m_button,
  "button-group": m_buttonGroup,
  "calendar": m_calendar,
  "card": m_card,
  "carousel": m_carousel,
  "chart": m_chart,
  "checkbox": m_checkbox,
  "chip": m_chip,
  "circular-progress": m_circularProgress,
  "collapsible": m_collapsible,
  "combobox": m_combobox,
  "command": m_command,
  "context-menu": m_contextMenu,
  "date-picker": m_datePicker,
  "dialog": m_dialog,
  "drawer": m_drawer,
  "dropdown-menu": m_dropdownMenu,
  "empty": m_empty,
  "expressive-carousel": m_expressiveCarousel,
  "fab": m_fab,
  "fab-menu": m_fabMenu,
  "field": m_field,
  "hover-card": m_hoverCard,
  "icon": m_icon,
  "input": m_input,
  "input-group": m_inputGroup,
  "input-otp": m_inputOtp,
  "item": m_item,
  "kbd": m_kbd,
  "label": m_label,
  "loading-indicator": m_loadingIndicator,
  "m3-theme-scope": m_m3ThemeScope,
  "marker": m_marker,
  "menubar": m_menubar,
  "message": m_message,
  "message-scroller": m_messageScroller,
  "native-select": m_nativeSelect,
  "navigation": m_navigation,
  "navigation-menu": m_navigationMenu,
  "pagination": m_pagination,
  "popover": m_popover,
  "portal-container": m_portalContainer,
  "progress": m_progress,
  "questionnaire": m_questionnaire,
  "radio-group": m_radioGroup,
  "resizable": m_resizable,
  "scroll-area": m_scrollArea,
  "search": m_search,
  "select": m_select,
  "separator": m_separator,
  "shape": m_shape,
  "sheet": m_sheet,
  "side-sheet": m_sideSheet,
  "sidebar": m_sidebar,
  "skeleton": m_skeleton,
  "slider": m_slider,
  "sonner": m_sonner,
  "spinner": m_spinner,
  "split-button": m_splitButton,
  "switch": m_switch,
  "table": m_table,
  "tabs": m_tabs,
  "text-field": m_textField,
  "textarea": m_textarea,
  "time-picker": m_timePicker,
  "toast": m_toast,
  "toggle": m_toggle,
  "toggle-group": m_toggleGroup,
  "toolbar": m_toolbar,
  "tooltip": m_tooltip,
};
