import type { Choice, Labels, PartDef, PartLang, PropDef } from "./types";

/* The translations of the parts' own words: what the palette, the panel and the layers call a
 * part, what it calls its props, and the seed text a fresh part carries. `label`/`name`/`default`
 * on the defs stay English (the docs' canonical names and the code's vocabulary); these tables
 * hold what the editor shows in Japanese, Chinese and Korean. A def can still set `labels` or
 * `defaults` on a single entry; the tables below are only the fallback. */

/** the part's name in the palette and the panels, by slug */
export const PART_NAMES: Record<string, Labels> = {
  // actions
  button: { ja: "ボタン", zh: "按钮", ko: "버튼" },
  fab: { ja: "フローティングボタン", zh: "悬浮按钮", ko: "플로팅 버튼" },
  chip: { ja: "チップ", zh: "纸片", ko: "칩" },
  toggle: { ja: "トグル", zh: "切换按钮", ko: "토글" },
  "toggle-group": { ja: "トグルグループ", zh: "切换按钮组", ko: "토글 그룹" },
  "button-group": { ja: "ボタングループ", zh: "按钮组", ko: "버튼 그룹" },
  "split-button": { ja: "スプリットボタン", zh: "分段按钮", ko: "분할 버튼" },
  "fab-menu": { ja: "FAB メニュー", zh: "悬浮菜单", ko: "FAB 메뉴" },
  // chat
  message: { ja: "メッセージ", zh: "消息", ko: "메시지" },
  bubble: { ja: "バブル", zh: "气泡", ko: "말풍선" },
  marker: { ja: "マーカー", zh: "标记", ko: "마커" },
  attachment: { ja: "添付ファイル", zh: "附件", ko: "첨부" },
  "message-scroller": { ja: "メッセージスクローラー", zh: "消息滚动区", ko: "메시지 스크롤" },
  questionnaire: { ja: "質問票", zh: "问卷", ko: "설문" },
  // communication
  badge: { ja: "バッジ", zh: "徽章", ko: "배지" },
  progress: { ja: "プログレス", zh: "进度条", ko: "진행률" },
  "circular-progress": { ja: "円形プログレス", zh: "环形进度", ko: "원형 진행률" },
  "loading-indicator": { ja: "ローディング", zh: "加载指示", ko: "로딩" },
  spinner: { ja: "スピナー", zh: "加载圈", ko: "스피너" },
  skeleton: { ja: "スケルトン", zh: "骨架屏", ko: "스켈레톤" },
  sonner: { ja: "スナックバー", zh: "提示条", ko: "스낵바" },
  tooltip: { ja: "ツールチップ", zh: "工具提示", ko: "툴팁" },
  alert: { ja: "アラート", zh: "警告", ko: "알림" },
  // containment
  card: { ja: "カード", zh: "卡片", ko: "카드" },
  item: { ja: "リスト項目", zh: "列表项", ko: "목록 항목" },
  dialog: { ja: "ダイアログ", zh: "对话框", ko: "대화상자" },
  "alert-dialog": { ja: "確認ダイアログ", zh: "确认对话框", ko: "확인 대화상자" },
  sheet: { ja: "シート", zh: "面板", ko: "시트" },
  "side-sheet": { ja: "サイドシート", zh: "侧面板", ko: "사이드 시트" },
  drawer: { ja: "ドロワー", zh: "抽屉", ko: "드로어" },
  popover: { ja: "ポップオーバー", zh: "弹出框", ko: "팝오버" },
  "hover-card": { ja: "ホバーカード", zh: "悬停卡片", ko: "호버 카드" },
  accordion: { ja: "アコーディオン", zh: "折叠面板", ko: "아코디언" },
  collapsible: { ja: "折りたたみ", zh: "可折叠", ko: "접이식" },
  separator: { ja: "区切り線", zh: "分隔线", ko: "구분선" },
  "scroll-area": { ja: "スクロール領域", zh: "滚动区", ko: "스크롤 영역" },
  resizable: { ja: "リサイズ可能", zh: "可调整大小", ko: "크기 조절" },
  // content
  icon: { ja: "アイコン", zh: "图标", ko: "아이콘" },
  avatar: { ja: "アバター", zh: "头像", ko: "아바타" },
  carousel: { ja: "カルーセル", zh: "轮播", ko: "캐러셀" },
  "expressive-carousel": { ja: "エクスプレッシブカルーセル", zh: "表现力轮播", ko: "표현형 캐러셀" },
  table: { ja: "テーブル", zh: "表格", ko: "표" },
  chart: { ja: "チャート", zh: "图表", ko: "차트" },
  kbd: { ja: "キー", zh: "按键", ko: "키" },
  "aspect-ratio": { ja: "アスペクト比", zh: "宽高比", ko: "가로세로비" },
  empty: { ja: "空の状態", zh: "空状态", ko: "빈 상태" },
  shape: { ja: "シェイプ", zh: "形状", ko: "모양" },
  // menus
  "dropdown-menu": { ja: "ドロップダウンメニュー", zh: "下拉菜单", ko: "드롭다운 메뉴" },
  "context-menu": { ja: "コンテキストメニュー", zh: "上下文菜单", ko: "컨텍스트 메뉴" },
  menubar: { ja: "メニューバー", zh: "菜单栏", ko: "메뉴바" },
  // navigation
  "navigation-bar": { ja: "ナビゲーションバー", zh: "导航栏", ko: "내비게이션 바" },
  "app-bar": { ja: "アプリバー", zh: "应用栏", ko: "앱 바" },
  tabs: { ja: "タブ", zh: "标签页", ko: "탭" },
  "navigation-rail": { ja: "ナビゲーションレール", zh: "侧边导航", ko: "내비게이션 레일" },
  toolbar: { ja: "ツールバー", zh: "工具栏", ko: "툴바" },
  breadcrumb: { ja: "パンくず", zh: "面包屑", ko: "브레드크럼" },
  pagination: { ja: "ページネーション", zh: "分页", ko: "페이지네이션" },
  "navigation-menu": { ja: "ナビゲーションメニュー", zh: "导航菜单", ko: "내비게이션 메뉴" },
  sidebar: { ja: "サイドバー", zh: "侧栏", ko: "사이드바" },
  search: { ja: "検索", zh: "搜索", ko: "검색" },
  command: { ja: "コマンド", zh: "命令", ko: "명령" },
  // pickers
  calendar: { ja: "カレンダー", zh: "日历", ko: "캘린더" },
  "date-picker": { ja: "日付ピッカー", zh: "日期选择器", ko: "날짜 선택기" },
  "time-picker": { ja: "時刻ピッカー", zh: "时间选择器", ko: "시간 선택기" },
  // selection
  switch: { ja: "スイッチ", zh: "开关", ko: "스위치" },
  checkbox: { ja: "チェックボックス", zh: "复选框", ko: "체크박스" },
  "radio-group": { ja: "ラジオボタン", zh: "单选按钮组", ko: "라디오 버튼" },
  slider: { ja: "スライダー", zh: "滑块", ko: "슬라이더" },
  select: { ja: "セレクト", zh: "选择器", ko: "선택기" },
  "native-select": { ja: "ネイティブセレクト", zh: "原生选择器", ko: "기본 선택기" },
  combobox: { ja: "コンボボックス", zh: "组合框", ko: "콤보박스" },
  // text inputs
  "text-field": { ja: "テキストフィールド", zh: "文本框", ko: "텍스트 필드" },
  input: { ja: "入力", zh: "输入框", ko: "입력" },
  textarea: { ja: "複数行入力", zh: "多行输入", ko: "여러 줄 입력" },
  "input-group": { ja: "入力グループ", zh: "输入组", ko: "입력 그룹" },
  "input-otp": { ja: "ワンタイムコード", zh: "一次性验证码", ko: "일회용 코드" },
  field: { ja: "フィールド", zh: "字段", ko: "필드" },
  label: { ja: "ラベル", zh: "标签", ko: "라벨" },
  // theming
  "theme-provider": { ja: "テーマプロバイダー", zh: "主题提供器", ko: "테마 프로바이더" },
};

/** prop labels and enum option labels shared across parts, by their English text */
export const COMMON_LABELS: Record<string, Labels> = {
  // prop labels
  Width: { ja: "幅", zh: "宽度", ko: "너비" },
  Height: { ja: "高さ", zh: "高度", ko: "높이" },
  Size: { ja: "サイズ", zh: "尺寸", ko: "크기" },
  Variant: { ja: "スタイル", zh: "样式", ko: "스타일" },
  "Button variant": { ja: "ボタンのスタイル", zh: "按钮样式", ko: "버튼 스타일" },
  "Trigger variant": { ja: "トリガーのスタイル", zh: "触发器样式", ko: "트리거 스타일" },
  Label: { ja: "ラベル", zh: "标签", ko: "라벨" },
  "Button label": { ja: "ボタンのラベル", zh: "按钮文字", ko: "버튼 라벨" },
  "Trigger label": { ja: "トリガーのラベル", zh: "触发器文字", ko: "트리거 라벨" },
  "Link text": { ja: "リンクのテキスト", zh: "链接文字", ko: "링크 텍스트" },
  Title: { ja: "タイトル", zh: "标题", ko: "제목" },
  Description: { ja: "説明", zh: "描述", ko: "설명" },
  Text: { ja: "テキスト", zh: "文本", ko: "텍스트" },
  Content: { ja: "内容", zh: "内容", ko: "내용" },
  Placeholder: { ja: "プレースホルダー", zh: "占位文本", ko: "플레이스홀더" },
  Icon: { ja: "アイコン", zh: "图标", ko: "아이콘" },
  Image: { ja: "画像", zh: "图片", ko: "이미지" },
  "Leading icon": { ja: "先頭アイコン", zh: "前置图标", ko: "앞 아이콘" },
  "Trailing icon": { ja: "末尾アイコン", zh: "末尾图标", ko: "뒤 아이콘" },
  "Icon (basic)": { ja: "アイコン", zh: "图标", ko: "아이콘" },
  Disabled: { ja: "無効", zh: "禁用", ko: "비활성화" },
  Selected: { ja: "選択状態", zh: "已选", ko: "선택됨" },
  "Selected (-1: none)": { ja: "選択（-1: なし）", zh: "选中（-1：无）", ko: "선택（-1: 없음）" },
  "Selected (filter)": { ja: "選択状態", zh: "已选", ko: "선택됨" },
  "Selected (filter, -1: none)": { ja: "選択（-1: なし）", zh: "选中（-1：无）", ko: "선택（-1: 없음）" },
  Lowered: { ja: "低い影", zh: "降低", ko: "낮은 그림자" },
  "Collapsed (extended)": { ja: "折りたたみ", zh: "折叠", ko: "접기" },
  Chips: { ja: "チップ", zh: "标签", ko: "칩" },
  Trailing: { ja: "末尾", zh: "尾部", ko: "끝" },
  "Switch on": { ja: "スイッチ ON", zh: "开关开启", ko: "스위치 켜짐" },
  "Inline (standard sheet)": { ja: "インライン（標準シート）", zh: "内嵌（标准底部表单）", ko: "인라인(표준 시트)" },
  Elevated: { ja: "エレベーション", zh: "阴影", ko: "엘리베이션" },
  "Badge count (0: none)": { ja: "バッジ数（0: なし）", zh: "角标数（0：无）", ko: "배지 수(0: 없음)" },
  "Badge on destination": { ja: "バッジの項目", zh: "角标位置", ko: "배지 항목" },
  "Second trailing icon": { ja: "末尾アイコン 2", zh: "第二末尾图标", ko: "끝 아이콘 2" },
  Scrolled: { ja: "スクロール時", zh: "已滚动", ko: "스크롤됨" },
  "Modal (expanded over content)": { ja: "モーダル（上に重ねる）", zh: "模态（浮于内容上）", ko: "모달(콘텐츠 위)" },
  "Compact items": { ja: "コンパクト", zh: "紧凑项", ko: "컴팩트" },
  "Opens on (modal)": { ja: "初期表示（モーダル）", zh: "初始视图（弹窗）", ko: "기본 보기(모달)" },
  "Slide width (0: full)": { ja: "スライド幅（0: 全幅）", zh: "滑块宽（0：全宽）", ko: "슬라이드 너비(0: 전체)" },
  "Slide width": { ja: "スライド幅", zh: "滑块宽", ko: "슬라이드 너비" },
  Gap: { ja: "間隔", zh: "间距", ko: "간격" },
  "Image position": { ja: "画像の位置", zh: "图片位置", ko: "이미지 위치" },
  "Image size": { ja: "画像の大きさ", zh: "图片大小", ko: "이미지 크기" },
  "Placeholder icon": { ja: "代替アイコン", zh: "占位图标", ko: "플레이스홀더 아이콘" },
  "Text align": { ja: "テキスト揃え", zh: "文本对齐", ko: "텍스트 정렬" },
  "Content align": { ja: "コンテンツ揃え", zh: "内容对齐", ko: "콘텐츠 정렬" },
  "Height (0: auto)": { ja: "高さ（0: 自動）", zh: "高度（0：自动）", ko: "높이(0: 자동)" },
  Density: { ja: "密度", zh: "密度", ko: "밀도" },
  Interactive: { ja: "タップ可能", zh: "可点击", ko: "탭 가능" },
  None: { ja: "なし", zh: "无", ko: "없음" },
  Top: { ja: "上", zh: "上", ko: "위" },
  Bottom: { ja: "下", zh: "下", ko: "아래" },
  Background: { ja: "背景", zh: "背景", ko: "배경" },
  "full-screen": { ja: "全画面", zh: "全屏", ko: "전체 화면" },
  Checked: { ja: "チェック状態", zh: "已勾选", ko: "체크됨" },
  Error: { ja: "エラー", zh: "错误", ko: "오류" },
  Value: { ja: "値", zh: "值", ko: "값" },
  Orientation: { ja: "向き", zh: "方向", ko: "방향" },
  Side: { ja: "表示側", zh: "显示侧", ko: "표시 위치" },
  Options: { ja: "選択肢", zh: "选项", ko: "옵션" },
  Items: { ja: "項目", zh: "项目", ko: "항목" },
  Kind: { ja: "種類", zh: "类型", ko: "종류" },
  Color: { ja: "色", zh: "颜色", ko: "색상" },
  Shape: { ja: "形", zh: "形状", ko: "모양" },
  Style: { ja: "スタイル", zh: "样式", ko: "스타일" },
  Rows: { ja: "行数", zh: "行数", ko: "행 수" },
  Columns: { ja: "列数", zh: "列数", ko: "열 수" },
  Indeterminate: { ja: "不定", zh: "不确定", ko: "불확정" },
  Open: { ja: "開く", zh: "打开", ko: "열기" },
  Menu: { ja: "メニュー", zh: "菜单", ko: "메뉴" },
  Mode: { ja: "モード", zh: "模式", ko: "모드" },
  Length: { ja: "長さ", zh: "长度", ko: "길이" },
  Layout: { ja: "レイアウト", zh: "布局", ko: "레이아웃" },
  Home: { ja: "ホーム", zh: "首页", ko: "홈" },
  Share: { ja: "共有", zh: "分享", ko: "공유" },
  Settings: { ja: "設定", zh: "设置", ko: "설정" },
  Sent: { ja: "送信済み", zh: "已发送", ko: "보냄" },
  Received: { ja: "受信", zh: "已接收", ko: "받음" },
  Forward: { ja: "進む", zh: "前进", ko: "앞으로" },
  Destinations: { ja: "行き先", zh: "目的地", ko: "대상" },
  Control: { ja: "コントロール", zh: "控件", ko: "컨트롤" },
  Components: { ja: "部品", zh: "组件", ko: "구성 요소" },
  "Confirm action": { ja: "確定ボタン", zh: "确认操作", ko: "확인 작업" },
  "Dismiss action": { ja: "閉じるボタン", zh: "取消操作", ko: "닫기 작업" },
  "Dismiss action (basic)": { ja: "閉じるボタン", zh: "取消操作", ko: "닫기 작업" },
  "Cancel action": { ja: "キャンセルボタン", zh: "取消操作", ko: "취소 작업" },
  "Close action": { ja: "閉じるボタン", zh: "关闭操作", ko: "닫기 작업" },
  "Close button": { ja: "閉じるボタン", zh: "关闭按钮", ko: "닫기 버튼" },
  "Close button (basic)": { ja: "閉じるボタン", zh: "关闭按钮", ko: "닫기 버튼" },
  "Stacked actions": { ja: "ボタンを縦積み", zh: "按钮纵向排列", ko: "버튼 세로 배치" },
  "Stacked actions (basic)": { ja: "ボタンを縦積み", zh: "按钮纵向排列", ko: "버튼 세로 배치" },
  "Supporting text": { ja: "補足テキスト", zh: "辅助文本", ko: "보조 텍스트" },
  Slides: { ja: "スライド", zh: "幻灯片", ko: "슬라이드" },
  "Menu items": { ja: "メニュー項目", zh: "菜单项", ko: "메뉴 항목" },
  Buttons: { ja: "ボタン", zh: "按钮", ko: "버튼" },
  Actions: { ja: "アクション", zh: "操作", ko: "작업" },
  "Trigger icon": { ja: "トリガーのアイコン", zh: "触发器图标", ko: "트리거 아이콘" },
  "Avatar letter": { ja: "アバターの文字", zh: "头像文字", ko: "아바타 문자" },
  "Panel text": { ja: "パネルのテキスト", zh: "面板文字", ko: "패널 텍스트" },
  "First item open": { ja: "最初の項目を開く", zh: "展开第一项", ko: "첫 항목 열기" },
  "Several open at once": { ja: "複数同時に開く", zh: "同时展开多个", ko: "여러 개 동시에 열기" },
  "Swipe handle": { ja: "スワイプハンドル", zh: "拖动手柄", ko: "스와이프 핸들" },
  "Sheet width": { ja: "シートの幅", zh: "面板宽度", ko: "시트 너비" },
  "Frame height": { ja: "枠の高さ", zh: "框架高度", ko: "프레임 높이" },
  Detached: { ja: "分離", zh: "分离", ko: "분리" },
  "Apply and Cancel": { ja: "適用とキャンセル", zh: "应用与取消", ko: "적용 및 취소" },
  "Save and Cancel": { ja: "保存とキャンセル", zh: "保存与取消", ko: "저장 및 취소" },
  "Label (extended)": { ja: "ラベル（拡張）", zh: "标签（扩展）", ko: "라벨(확장)" },
  "Narrow (80dp)": { ja: "狭幅 (80dp)", zh: "窄 (80dp)", ko: "좁게 (80dp)" },
  "First panel": { ja: "最初のパネル", zh: "第一个面板", ko: "첫 번째 패널" },
  Scrollbars: { ja: "スクロールバー", zh: "滚动条", ko: "스크롤바" },
  "Row label": { ja: "行のラベル", zh: "行标签", ko: "행 라벨" },
  // enum option labels (display text only; raw code values are never translated)
  Basic: { ja: "基本", zh: "基本", ko: "기본" },
  "Full-screen": { ja: "全画面", zh: "全屏", ko: "전체 화면" },
  standard: { ja: "標準", zh: "标准", ko: "표준" },
  connected: { ja: "連結", zh: "连接", ko: "연결" },
  round: { ja: "角丸", zh: "圆角", ko: "둥근" },
  square: { ja: "四角", zh: "方形", ko: "사각" },
  horizontal: { ja: "横", zh: "水平", ko: "가로" },
  vertical: { ja: "縦", zh: "垂直", ko: "세로" },
  left: { ja: "左", zh: "左", ko: "왼쪽" },
  right: { ja: "右", zh: "右", ko: "오른쪽" },
  top: { ja: "上", zh: "上", ko: "위" },
  bottom: { ja: "下", zh: "下", ko: "아래" },
  start: { ja: "先頭", zh: "起始", ko: "시작" },
  end: { ja: "末尾", zh: "末尾", ko: "끝" },
  center: { ja: "中央", zh: "居中", ko: "가운데" },
  collapsed: { ja: "折りたたみ", zh: "折叠", ko: "접힘" },
  expanded: { ja: "展開", zh: "展开", ko: "펼침" },
  modal: { ja: "モーダル", zh: "模态", ko: "모달" },
  compact: { ja: "コンパクト", zh: "紧凑", ko: "컴팩트" },
  Connected: { ja: "連結", zh: "连接", ko: "연결" },
  Multiple: { ja: "複数", zh: "多个", ko: "여러 개" },
  Group: { ja: "グループ", zh: "组", ko: "그룹" },
  On: { ja: "オン", zh: "开", ko: "켬" },
  Range: { ja: "範囲", zh: "范围", ko: "범위" },
  "Range end": { ja: "範囲の終わり", zh: "范围结束", ko: "범위 끝" },
  "Clear button": { ja: "クリアボタン", zh: "清除按钮", ko: "지우기 버튼" },
  Multiline: { ja: "複数行", zh: "多行", ko: "여러 줄" },
  Type: { ja: "種類", zh: "类型", ko: "유형" },
  "Leading text": { ja: "先頭のテキスト", zh: "前置文字", ko: "앞 텍스트" },
  "Trailing text": { ja: "末尾のテキスト", zh: "末尾文字", ko: "뒤 텍스트" },
  "Trailing button": { ja: "末尾ボタン", zh: "末尾按钮", ko: "뒤 버튼" },
  "Group size (0: one group)": { ja: "グループ内の数（0: 1グループ）", zh: "每组数量（0：一组）", ko: "그룹당 개수(0: 한 그룹)" },
  "Error message": { ja: "エラーメッセージ", zh: "错误信息", ko: "오류 메시지" },
  "Icon (dot, count)": { ja: "アイコン（ドット・数）", zh: "图标（圆点、计数）", ko: "아이콘(점·개수)" },
  Count: { ja: "数", zh: "计数", ko: "개수" },
  "Show value": { ja: "値を表示", zh: "显示数值", ko: "값 표시" },
  Speed: { ja: "速度", zh: "速度", ko: "속도" },
  "Lines (text)": { ja: "行（テキスト）", zh: "行（文本）", ko: "줄(텍스트)" },
  "Height (block)": { ja: "高さ（ブロック）", zh: "高度（块）", ko: "높이(블록)" },
  Message: { ja: "メッセージ", zh: "消息", ko: "메시지" },
  "Action label": { ja: "アクションラベル", zh: "操作标签", ko: "작업 라벨" },
  "Tooltip text": { ja: "ツールチップ", zh: "工具提示文字", ko: "툴팁 텍스트" },
  "Action button": { ja: "アクションボタン", zh: "操作按钮", ko: "작업 버튼" },
  Thickness: { ja: "太さ", zh: "粗细", ko: "두께" },
  "Second panel": { ja: "2番目のパネル", zh: "第二个面板", ko: "두 번째 패널" },
  "First panel size": { ja: "最初のパネルのサイズ", zh: "第一个面板大小", ko: "첫 패널 크기" },
  "Grip on the handle": { ja: "ハンドルのグリップ", zh: "手柄上的握把", ko: "손잡이 그립" },
  Tall: { ja: "高くする", zh: "加高", ko: "높게" },
  Subtitle: { ja: "サブタイトル", zh: "副标题", ko: "부제" },
  "Centered (small)": { ja: "中央揃え（小）", zh: "居中（小）", ko: "가운데 정렬(소)" },
  Tabs: { ja: "タブ", zh: "标签页", ko: "탭" },
  Expanded: { ja: "展開", zh: "展开", ko: "펼침" },
  "Compose button": { ja: "作成ボタン", zh: "撰写按钮", ko: "작성 버튼" },
  "Color (floating)": { ja: "色（フローティング時）", zh: "颜色（浮动）", ko: "색상(플로팅)" },
  "Orientation (floating)": { ja: "向き（フローティング時）", zh: "方向（浮动）", ko: "방향(플로팅)" },
  "Width (docked)": { ja: "幅（ドック時）", zh: "宽度（停靠）", ko: "너비(도킹)" },
  Trail: { ja: "トレイル", zh: "拖尾", ko: "트레일" },
  Separator: { ja: "区切り", zh: "分隔符", ko: "구분선" },
  "Collapse the middle": { ja: "中央を折りたたむ", zh: "折叠中间", ko: "가운데 접기" },
  Pages: { ja: "ページ", zh: "页数", ko: "페이지" },
  "Current page": { ja: "現在のページ", zh: "当前页", ko: "현재 페이지" },
  "Previous label": { ja: "「前へ」のラベル", zh: "“上一页”文字", ko: "'이전' 라벨" },
  "Next label": { ja: "「次へ」のラベル", zh: "“下一页”文字", ko: "'다음' 라벨" },
  "Menu triggers": { ja: "メニューのトリガー", zh: "菜单触发器", ko: "메뉴 트리거" },
  "Links in each menu": { ja: "各メニューのリンク", zh: "每个菜单的链接", ko: "메뉴별 링크" },
  "Plain links": { ja: "通常のリンク", zh: "普通链接", ko: "일반 링크" },
  "Group label": { ja: "グループのラベル", zh: "组标签", ko: "그룹 라벨" },
  "Item size": { ja: "項目のサイズ", zh: "项目大小", ko: "항목 크기" },
  "Size (view)": { ja: "サイズ（ビュー）", zh: "大小（视图）", ko: "크기(뷰)" },
  "Suggestions (view)": { ja: "候補（ビュー）", zh: "建议（视图）", ko: "추천(뷰)" },
  "Group heading": { ja: "グループの見出し", zh: "组标题", ko: "그룹 제목" },
  Commands: { ja: "コマンド", zh: "命令", ko: "명령" },
  "Destructive item": { ja: "破壊的な項目", zh: "危险项", ko: "파괴적 항목" },
  "Area text": { ja: "領域のテキスト", zh: "区域文字", ko: "영역 텍스트" },
  Menus: { ja: "メニュー", zh: "菜单", ko: "메뉴" },
  "Items in each menu": { ja: "各メニューの項目数", zh: "每个菜单的项数", ko: "메뉴별 항목 수" },
  "Months shown": { ja: "表示する月数", zh: "显示月份数", ko: "표시할 월 수" },
  "Days of other months": { ja: "他の月の日付", zh: "其他月份的日期", ko: "다른 달 날짜" },
  "Week starts on": { ja: "週の始まり", zh: "一周开始于", ko: "주 시작 요일" },
  "Placeholder (docked)": { ja: "プレースホルダー（ドック時）", zh: "占位文本（停靠）", ko: "플레이스홀더(도킹)" },
  "Mode (modal)": { ja: "モード（モーダル時）", zh: "模式（模态）", ko: "모드(모달)" },
  "Title (modal)": { ja: "タイトル（モーダル時）", zh: "标题（模态）", ko: "제목(모달)" },
  "Disabled (docked)": { ja: "無効（ドック時）", zh: "禁用（停靠）", ko: "비활성화(도킹)" },
  Hours: { ja: "時", zh: "小时", ko: "시" },
  Minutes: { ja: "分", zh: "分钟", ko: "분" },
  "24-hour clock": { ja: "24時間表記", zh: "24小时制", ko: "24시간제" },
  Filled: { ja: "塗りつぶし", zh: "填充", ko: "채움" },
  Initials: { ja: "イニシャル", zh: "首字母", ko: "이니셜" },
  "People (a group when more than one)": { ja: "人数（2人以上でグループ）", zh: "人数（多于一人为组）", ko: "사람 수(2명 이상이면 그룹)" },
  Arrows: { ja: "矢印", zh: "箭头", ko: "화살표" },
  "Slide height": { ja: "スライドの高さ", zh: "幻灯片高度", ko: "슬라이드 높이" },
  "Selected row (0 for none)": { ja: "選択行（0 でなし）", zh: "选中行（0 为无）", ko: "선택 행(0이면 없음)" },
  Caption: { ja: "キャプション", zh: "标题", ko: "캡션" },
  Months: { ja: "月", zh: "月份", ko: "개월" },
  Series: { ja: "系列", zh: "系列", ko: "계열" },
  Keys: { ja: "キー", zh: "键", ko: "키" },
  Ratio: { ja: "比率", zh: "比例", ko: "비율" },
  "Dashed border": { ja: "破線の枠", zh: "虚线边框", ko: "점선 테두리" },
  Bubble: { ja: "バブル", zh: "气泡", ko: "말풍선" },
  "Avatar initials": { ja: "アバターのイニシャル", zh: "头像首字母", ko: "아바타 이니셜" },
  Sender: { ja: "送信者", zh: "发送者", ko: "보낸 사람" },
  Footer: { ja: "フッター", zh: "页脚", ko: "푸터" },
  Reaction: { ja: "リアクション", zh: "回应", ko: "리액션" },
  State: { ja: "状態", zh: "状态", ko: "상태" },
  "Remove button": { ja: "削除ボタン", zh: "移除按钮", ko: "삭제 버튼" },
  "Messages (they alternate between received and sent)": { ja: "メッセージ（受信と送信で交互）", zh: "消息（收发交替）", ko: "메시지(수신·발신 교대)" },
  "Jump to newest button": { ja: "最新へ移動ボタン", zh: "跳到最新按钮", ko: "최신으로 이동 버튼" },
  Question: { ja: "質問", zh: "问题", ko: "질문" },
  Hint: { ja: "ヒント", zh: "提示", ko: "힌트" },
  Choices: { ja: "選択肢", zh: "选项", ko: "선택지" },
  "Several answers": { ja: "複数回答可", zh: "可多选", ko: "복수 응답" },
  Questions: { ja: "質問数", zh: "问题数", ko: "질문 수" },
  "Seed color": { ja: "ベースの色", zh: "基准色", ko: "기본 색상" },
  Contrast: { ja: "コントラスト", zh: "对比度", ko: "대비" },
  Spec: { ja: "スペック", zh: "规范", ko: "스펙" },
  // enum option labels that are words the author reads, not code values
  filled: { ja: "塗りつぶし", zh: "填充", ko: "채움" },
  tonal: { ja: "トーナル", zh: "色调", ko: "토널" },
  elevated: { ja: "浮き上がり", zh: "凸起", ko: "입체" },
  outlined: { ja: "枠線", zh: "描边", ko: "윤곽" },
  text: { ja: "テキスト", zh: "文本", ko: "텍스트" },
  narrow: { ja: "狭い", zh: "窄", ko: "좁게" },
  wide: { ja: "広い", zh: "宽", ko: "넓게" },
  flat: { ja: "フラット", zh: "扁平", ko: "플랫" },
  outline: { ja: "枠線", zh: "描边", ko: "윤곽" },
  ghost: { ja: "ゴースト", zh: "幽灵", ko: "고스트" },
  link: { ja: "リンク", zh: "链接", ko: "링크" },
  destructive: { ja: "破壊的", zh: "危险", ko: "파괴적" },
  assist: { ja: "アシスト", zh: "辅助", ko: "어시스트" },
  filter: { ja: "フィルター", zh: "筛选", ko: "필터" },
  input: { ja: "入力", zh: "输入", ko: "입력" },
  suggestion: { ja: "候補", zh: "建议", ko: "추천" },
  small: { ja: "小", zh: "小", ko: "작음" },
  medium: { ja: "中", zh: "中", ko: "중간" },
  large: { ja: "大", zh: "大", ko: "큼" },
  default: { ja: "既定", zh: "默认", ko: "기본" },
  single: { ja: "単一", zh: "单个", ko: "단일" },
  multiple: { ja: "複数", zh: "多个", ko: "여러" },
  range: { ja: "範囲", zh: "范围", ko: "범위" },
  sunday: { ja: "日曜", zh: "周日", ko: "일요일" },
  monday: { ja: "月曜", zh: "周一", ko: "월요일" },
  dial: { ja: "ダイヤル", zh: "表盘", ko: "다이얼" },
  "multi-browse": { ja: "マルチブラウズ", zh: "多图浏览", ko: "멀티 브라우즈" },
  hero: { ja: "ヒーロー", zh: "主图", ko: "히어로" },
  uncontained: { ja: "枠なし", zh: "无容器", ko: "테두리 없음" },
  floating: { ja: "フローティング", zh: "浮动", ko: "플로팅" },
  docked: { ja: "ドック", zh: "停靠", ko: "도킹" },
  vibrant: { ja: "鮮やか", zh: "鲜艳", ko: "선명" },
  muted: { ja: "控えめ", zh: "柔和", ko: "차분" },
  segmented: { ja: "セグメント", zh: "分段", ko: "세그먼트" },
  both: { ja: "両方", zh: "两者", ko: "둘 다" },
  column: { ja: "縦積み", zh: "纵排", ko: "세로 배치" },
  row: { ja: "横並び", zh: "横排", ko: "가로 배치" },
  error: { ja: "エラー", zh: "错误", ko: "오류" },
  wavy: { ja: "波形", zh: "波浪形", ko: "물결" },
  contained: { ja: "コンテナ", zh: "容器", ko: "컨테이너" },
  info: { ja: "情報", zh: "信息", ko: "정보" },
  baseline: { ja: "ベースライン", zh: "基线", ko: "베이스라인" },
  tonalSpot: { ja: "トーンスポット", zh: "色调点", ko: "톤 스폿" },
  expressive: { ja: "表現", zh: "表现力", ko: "표현형" },
  neutral: { ja: "ニュートラル", zh: "中性", ko: "뉴트럴" },
  fidelity: { ja: "忠実", zh: "保真", ko: "충실" },
  content: { ja: "コンテンツ", zh: "内容", ko: "콘텐츠" },
  rainbow: { ja: "レインボー", zh: "彩虹", ko: "레인보우" },
  fruitSalad: { ja: "フルーツサラダ", zh: "水果沙拉", ko: "과일 샐러드" },
  monochrome: { ja: "モノクロ", zh: "单色", ko: "모노크롬" },
  high: { ja: "高", zh: "高", ko: "높음" },
  done: { ja: "完了", zh: "完成", ko: "완료" },
  idle: { ja: "待機", zh: "空闲", ko: "대기" },
  uploading: { ja: "アップロード中", zh: "上传中", ko: "업로드 중" },
  processing: { ja: "処理中", zh: "处理中", ko: "처리 중" },
  separator: { ja: "区切り線", zh: "分隔线", ko: "구분선" },
  border: { ja: "枠線", zh: "边框", ko: "테두리" },
  tinted: { ja: "ティント", zh: "着色", ko: "틴트" },
  "Dot on an icon": { ja: "アイコン上のドット", zh: "图标上的圆点", ko: "아이콘 점" },
  "Count on an icon": { ja: "アイコン上の数", zh: "图标上的计数", ko: "아이콘 숫자" },
  "Avatar and lines": { ja: "アバターと行", zh: "头像和文本行", ko: "아바타와 줄" },
  "Text lines": { ja: "テキスト行", zh: "文本行", ko: "텍스트 줄" },
  Card: { ja: "カード", zh: "卡片", ko: "카드" },
  Block: { ja: "ブロック", zh: "块", ko: "블록" },
  "Search view": { ja: "検索ビュー", zh: "搜索视图", ko: "검색 뷰" },
  "Search bar": { ja: "検索バー", zh: "搜索栏", ko: "검색 바" },
  "Toggle buttons": { ja: "トグルボタン", zh: "切换按钮", ko: "토글 버튼" },
  "Toggle button": { ja: "トグルボタン", zh: "切换按钮", ko: "토글 버튼" },
  "Icon when on": { ja: "オンのときのアイコン", zh: "开启时的图标", ko: "켰을 때 아이콘" },
  "Label when on": { ja: "オンのときのラベル", zh: "开启时的标签", ko: "켰을 때 라벨" },
  "Menu button": { ja: "メニューボタン", zh: "菜单按钮", ko: "메뉴 버튼" },
};

/** seed text a fresh part carries, by the English default */
export const COMMON_TEXT: Record<string, Labels> = {
  Button: { ja: "ボタン", zh: "按钮", ko: "버튼" },
  Chip: { ja: "チップ", zh: "纸片", ko: "칩" },
  Cancel: { ja: "キャンセル", zh: "取消", ko: "취소" },
  Accept: { ja: "OK", zh: "确定", ko: "확인" },
  Delete: { ja: "削除", zh: "删除", ko: "삭제" },
  Close: { ja: "閉じる", zh: "关闭", ko: "닫기" },
  Save: { ja: "保存", zh: "保存", ko: "저장" },
  Apply: { ja: "適用", zh: "应用", ko: "적용" },
  Search: { ja: "検索", zh: "搜索", ko: "검색" },
  Send: { ja: "送信", zh: "发送", ko: "보내기" },
  Edit: { ja: "編集", zh: "编辑", ko: "편집" },
  Back: { ja: "戻る", zh: "返回", ko: "뒤로" },
  Next: { ja: "次へ", zh: "下一步", ko: "다음" },
  Done: { ja: "完了", zh: "完成", ko: "완료" },
  "Card title": { ja: "カードの見出し", zh: "卡片标题", ko: "카드 제목" },
  "Supporting text for the card.": { ja: "カードの補足テキストがここに入ります。", zh: "卡片的辅助文字写在这里。", ko: "카드의 보조 텍스트가 여기에 들어갑니다." },
  Inbox: { ja: "受信トレイ", zh: "收件箱", ko: "받은편지함" },
  Starred: { ja: "スター付き", zh: "已加星标", ko: "별표 표시" },
  Archive: { ja: "アーカイブ", zh: "归档", ko: "보관함" },
  Favorite: { ja: "お気に入り", zh: "收藏", ko: "즐겨찾기" },
  "Supporting text": { ja: "サブテキスト", zh: "辅助文本", ko: "보조 텍스트" },
  "Get started": { ja: "はじめる", zh: "开始", ko: "시작하기" },
  "12 new messages": { ja: "新着 12 件", zh: "12 条新消息", ko: "새 메시지 12개" },
  "Reset settings?": { ja: "設定をリセットしますか？", zh: "重置设置？", ko: "설정을 초기화할까요?" },
  "This will reset your app preferences back to their default settings.": {
    ja: "アプリの設定を初期値に戻します。",
    zh: "这将把应用偏好重置为默认设置。",
    ko: "앱 환경 설정을 기본값으로 되돌립니다.",
  },
  "This action cannot be undone.": { ja: "この操作は元に戻せません。", zh: "此操作无法撤销。", ko: "이 작업은 되돌릴 수 없습니다." },
  "Delete your account?": { ja: "アカウントを削除しますか？", zh: "删除您的账户？", ko: "계정을 삭제할까요?" },
  "Delete account": { ja: "アカウントを削除", zh: "删除账户", ko: "계정 삭제" },
  Filters: { ja: "絞り込み", zh: "筛选", ko: "필터" },
  "Narrow down the results.": { ja: "結果を絞り込みます。", zh: "缩小结果范围。", ko: "결과를 좁힙니다." },
  "Choose where to send this.": { ja: "送信先を選んでください。", zh: "选择发送位置。", ko: "보낼 곳을 선택하세요." },
  "Toggle details": { ja: "詳細の表示切替", zh: "切换详情", ko: "세부 정보 전환" },
  "Here are the details that were hidden.": { ja: "隠れていた詳細です。", zh: "这里是被隐藏的内容。", ko: "숨겨져 있던 내용입니다." },
  Day: { ja: "日", zh: "天", ko: "일" },
  Week: { ja: "週", zh: "周", ko: "주" },
  Month: { ja: "月", zh: "月", ko: "월" },
  Year: { ja: "年", zh: "年", ko: "년" },
  Rewind: { ja: "巻き戻し", zh: "快退", ko: "되감기" },
  Play: { ja: "再生", zh: "播放", ko: "재생" },
  Duplicate: { ja: "複製", zh: "复制", ko: "복제" },
  Share: { ja: "共有", zh: "分享", ko: "공유" },
  Mail: { ja: "メール", zh: "邮件", ko: "메일" },
  Event: { ja: "予定", zh: "日程", ko: "일정" },
  Task: { ja: "タスク", zh: "任务", ko: "할 일" },
  Item: { ja: "項目", zh: "项目", ko: "항목" },
  Left: { ja: "左", zh: "左", ko: "왼쪽" },
  Right: { ja: "右", zh: "右", ko: "오른쪽" },
  "@material": { ja: "@material", zh: "@material", ko: "@material" },
  M: { ja: "M", zh: "M", ko: "M" },
  "Material Design": { ja: "Material Design", zh: "Material Design", ko: "Material Design" },
  "Google's open-source design system.": {
    ja: "Google のオープンソースデザインシステム。",
    zh: "Google 的开源设计系统。",
    ko: "Google의 오픈 소스 디자인 시스템.",
  },
  "Set the size of the layer.": { ja: "レイヤーのサイズを設定します。", zh: "设置图层大小。", ko: "레이어 크기를 설정합니다." },
  Dimensions: { ja: "寸法", zh: "尺寸", ko: "치수" },
  "What is M3 Expressive?": { ja: "M3 Expressive とは？", zh: "什么是 M3 Expressive？", ko: "M3 Expressive란?" },
  "Where do the values come from?": { ja: "値はどこから来るの？", zh: "值从何而来？", ko: "값은 어디서 오는가?" },
  "Can I use it with shadcn?": { ja: "shadcn と一緒に使える？", zh: "可以和 shadcn 一起用吗？", ko: "shadcn과 함께 쓸 수 있나요?" },
  "An expansion of Material 3 with richer shapes, springier motion and bolder type.": {
    ja: "Material 3 を拡張し、より豊かな形・ばねのような動き・大胆な書体を備えたもの。",
    zh: "Material 3 的扩展，具有更丰富的形状、更有弹性的动效和更大胆的字体。",
    ko: "Material 3를 확장해 더 풍부한 모양, 탄력 있는 모션, 과감한 서체를 갖춘 것.",
  },
  "Accept terms": { ja: "利用規約に同意", zh: "接受条款", ko: "약관 동의" },
  "Accept terms and conditions": { ja: "利用規約に同意する", zh: "接受条款和条件", ko: "이용약관에 동의" },
  "Select a fruit": { ja: "フルーツを選択", zh: "选择水果", ko: "과일 선택" },
  "Select a framework": { ja: "フレームワークを選択", zh: "选择框架", ko: "프레임워크 선택" },
  "Select date": { ja: "日付を選択", zh: "选择日期", ko: "날짜 선택" },
  "Select time": { ja: "時刻を選択", zh: "选择时间", ko: "시간 선택" },
  Label: { ja: "ラベル", zh: "标签", ko: "라벨" },
  Title: { ja: "タイトル", zh: "标题", ko: "제목" },
  Email: { ja: "メールアドレス", zh: "邮箱", ko: "이메일" },
  "Type your message here.": { ja: "ここにメッセージを入力", zh: "在此输入消息", ko: "여기에 메시지를 입력" },
  "Search...": { ja: "検索…", zh: "搜索…", ko: "검색…" },
  "We will never share it.": { ja: "共有されることはありません。", zh: "我们不会分享它。", ko: "공유되지 않습니다." },
  Badge: { ja: "バッジ", zh: "徽章", ko: "배지" },
  "Show snackbar": { ja: "スナックバーを表示", zh: "显示提示条", ko: "스낵바 표시" },
  "Message sent": { ja: "メッセージを送信しました", zh: "消息已发送", ko: "메시지를 보냈습니다" },
  "Hover me": { ja: "ホバーして", zh: "悬停查看", ko: "마우스를 올리세요" },
  "Add to library": { ja: "ライブラリに追加", zh: "添加到库", ko: "라이브러리에 추가" },
  "Heads up": { ja: "お知らせ", zh: "提醒", ko: "알림" },
  "You can change this in settings.": { ja: "設定で変更できます。", zh: "可以在设置中更改。", ko: "설정에서 변경할 수 있습니다." },
  "Narrow the messages down by sender, date or label.": { ja: "送信者・日付・ラベルで絞り込みます。", zh: "按发件人、日期或标签筛选。", ko: "보낸 사람, 날짜, 라벨로 좁힙니다." },
  "Open popover": { ja: "ポップオーバーを開く", zh: "打开弹出框", ko: "팝오버 열기" },
  "Open menu": { ja: "メニューを開く", zh: "打开菜单", ko: "메뉴 열기" },
  Previous: { ja: "前へ", zh: "上一页", ko: "이전" },
  Application: { ja: "アプリ", zh: "应用", ko: "애플리케이션" },
  "Search songs": { ja: "曲を検索", zh: "搜索歌曲", ko: "노래 검색" },
  "Type a command or search...": { ja: "コマンドまたは検索を入力…", zh: "输入命令或搜索…", ko: "명령 또는 검색 입력…" },
  Suggestions: { ja: "候補", zh: "建议", ko: "추천" },
  Suggestion: { ja: "候補", zh: "建议", ko: "추천" },
  "Right click here": { ja: "ここを右クリック", zh: "右键点击此处", ko: "여기를 우클릭" },
  Reload: { ja: "再読み込み", zh: "重新加载", ko: "새로고침" },
  File: { ja: "ファイル", zh: "文件", ko: "파일" },
  View: { ja: "表示", zh: "视图", ko: "보기" },
  "New tab": { ja: "新しいタブ", zh: "新建标签页", ko: "새 탭" },
  "New window": { ja: "新しいウィンドウ", zh: "新建窗口", ko: "새 창" },
  Print: { ja: "印刷", zh: "打印", ko: "인쇄" },
  Undo: { ja: "元に戻す", zh: "撤销", ko: "실행 취소" },
  Redo: { ja: "やり直し", zh: "重做", ko: "다시 실행" },
  Bold: { ja: "太字", zh: "粗体", ko: "굵게" },
  Italic: { ja: "斜体", zh: "斜体", ko: "기울임" },
  Components: { ja: "部品", zh: "组件", ko: "구성 요소" },
  Breadcrumb: { ja: "パンくず", zh: "面包屑", ko: "브레드크럼" },
  "Getting started": { ja: "はじめに", zh: "开始使用", ko: "시작하기" },
  Introduction: { ja: "はじめに", zh: "介绍", ko: "소개" },
  Installation: { ja: "インストール", zh: "安装", ko: "설치" },
  Theming: { ja: "テーマ設定", zh: "主题", ko: "테마" },
  Docs: { ja: "ドキュメント", zh: "文档", ko: "문서" },
  Birthday: { ja: "誕生日", zh: "生日", ko: "생일" },
  "No messages": { ja: "メッセージはありません", zh: "暂无消息", ko: "메시지 없음" },
  "New messages will show up here.": { ja: "新しいメッセージがここに表示されます。", zh: "新消息将显示在这里。", ko: "새 메시지가 여기에 표시됩니다." },
  Compose: { ja: "作成", zh: "撰写", ko: "작성" },
  "How can I help?": { ja: "何かお手伝いしましょうか？", zh: "有什么可以帮您？", ko: "무엇을 도와드릴까요?" },
  "Sounds good, see you then.": { ja: "了解、また後で。", zh: "好的，到时见。", ko: "알겠어요, 그때 봐요." },
  Today: { ja: "今日", zh: "今天", ko: "오늘" },
  "Hi! Ask me anything.": { ja: "こんにちは！なんでも聞いてください。", zh: "你好！尽管问我。", ko: "안녕하세요! 무엇이든 물어보세요." },
  "What is a spatial spring?": { ja: "空間スプリングとは？", zh: "什么是空间弹簧？", ko: "공간 스프링이란?" },
  "One that moves things, and may overshoot a little.": { ja: "物を動かし、少し行き過ぎることもあるもの", zh: "让物体移动并可能轻微过冲的机制", ko: "대상을 움직이며 조금 오버슈트할 수 있는 것" },
  "Thanks!": { ja: "ありがとう！", zh: "谢谢！", ko: "고마워요!" },
  "Which framework do you use?": { ja: "どのフレームワークを使っていますか？", zh: "你使用哪个框架？", ko: "어떤 프레임워크를 쓰나요?" },
  "Pick one.": { ja: "ひとつ選んでください。", zh: "选一个。", ko: "하나를 고르세요." },
  Home: { ja: "ホーム", zh: "首页", ko: "홈" },
  Saved: { ja: "保存済み", zh: "已保存", ko: "저장됨" },
  Settings: { ja: "設定", zh: "设置", ko: "설정" },
  Flights: { ja: "フライト", zh: "航班", ko: "항공편" },
  Trips: { ja: "旅行", zh: "行程", ko: "여행" },
  Explore: { ja: "見つける", zh: "探索", ko: "둘러보기" },
  Apple: { ja: "りんご", zh: "苹果", ko: "사과" },
  Banana: { ja: "バナナ", zh: "香蕉", ko: "바나나" },
  Cherry: { ja: "さくらんぼ", zh: "樱桃", ko: "체리" },
  "Option A": { ja: "選択肢 A", zh: "选项 A", ko: "옵션 A" },
  "Option B": { ja: "選択肢 B", zh: "选项 B", ko: "옵션 B" },
  "Option C": { ja: "選択肢 C", zh: "选项 C", ko: "옵션 C" },
  Default: { ja: "既定", zh: "默认", ko: "기본" },
  Comfortable: { ja: "標準", zh: "舒适", ko: "편안" },
  Compact: { ja: "コンパクト", zh: "紧凑", ko: "컴팩트" },
  Forward: { ja: "早送り", zh: "快进", ko: "빨리 감기" },
  "Recent search": { ja: "最近の検索", zh: "最近搜索", ko: "최근 검색" },
  "Another recent search": { ja: "別の最近の検索", zh: "另一个最近搜索", ko: "다른 최근 검색" },
  Calendar: { ja: "カレンダー", zh: "日历", ko: "캘린더" },
  "Search emoji": { ja: "絵文字を検索", zh: "搜索表情", ko: "이모지 검색" },
  Calculator: { ja: "電卓", zh: "计算器", ko: "계산기" },
  Preview: { ja: "プレビュー", zh: "预览", ko: "미리보기" },
  Rename: { ja: "名前を変更", zh: "重命名", ko: "이름 바꾸기" },
  Sunrise: { ja: "朝焼け", zh: "日出", ko: "일출" },
  Forest: { ja: "森", zh: "森林", ko: "숲" },
  Ocean: { ja: "海", zh: "海洋", ko: "바다" },
  Desert: { ja: "砂漠", zh: "沙漠", ko: "사막" },
  Glacier: { ja: "氷河", zh: "冰川", ko: "빙하" },
  Canyon: { ja: "峡谷", zh: "峡谷", ko: "협곡" },
  Invoice: { ja: "請求書", zh: "发票", ko: "청구서" },
  Status: { ja: "ステータス", zh: "状态", ko: "상태" },
  Amount: { ja: "金額", zh: "金额", ko: "금액" },
  "Recent invoices": { ja: "最近の請求書", zh: "最近的发票", ko: "최근 청구서" },
};

/** the label a prop or a choice shows, in the editor's language */
export function labelOf(l: { label: string; labels?: Labels }, lang: PartLang): string {
  return l.labels?.[lang] ?? COMMON_LABELS[l.label]?.[lang] ?? l.label;
}

/** the part's name, in the editor's language */
export function nameOf(def: Pick<PartDef, "slug" | "name" | "labels">, lang: PartLang): string {
  return def.labels?.[lang] ?? PART_NAMES[def.slug]?.[lang] ?? def.name;
}

/** what an enum choice is called, in the editor's language; a bare string is a code value and stays */
export function choiceLabelOf(c: Choice, lang: PartLang): string {
  if (typeof c === "string") return COMMON_LABELS[c]?.[lang] ?? c;
  return c.labels?.[lang] ?? COMMON_LABELS[c.label]?.[lang] ?? c.label;
}

/** the seed a text prop starts with, in the editor's language */
export function defaultTextOf(d: Extract<PropDef, { kind: "text" }>, lang: PartLang): string {
  return d.defaults?.[lang] ?? COMMON_TEXT[d.default]?.[lang] ?? d.default;
}

/** a list row's seed label, in the editor's language */
export const listTextOf = (label: string, lang: PartLang): string => COMMON_TEXT[label]?.[lang] ?? label;
