/**
 * Generates `src/styles/m3e.generated.css`:
 *  - the default color scheme (official M3 Expressive baseline)
 *  - the M3 Expressive motion springs as CSS `linear()` easings
 *
 * Run with `bun run gen:tokens`.
 */
import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import { themeCss } from "../src/lib/m3e/color"

const OUT = fileURLToPath(
  new URL("../src/styles/m3e.generated.css", import.meta.url)
)

/* ---------- springs ---------- */

/** position (0 -> 1) of a unit-mass spring at time t */
function spring(stiffness: number, dampingRatio: number) {
  const w0 = Math.sqrt(stiffness)
  const z = dampingRatio
  if (z < 1) {
    const wd = w0 * Math.sqrt(1 - z * z)
    return (t: number) =>
      1 -
      Math.exp(-z * w0 * t) *
        (Math.cos(wd * t) + ((z * w0) / wd) * Math.sin(wd * t))
  }
  return (t: number) => 1 - Math.exp(-w0 * t) * (1 + w0 * t)
}

/** time until the spring stays within `eps` of its target */
function settleTime(x: (t: number) => number, eps = 0.001) {
  let last = 0
  for (let t = 0; t < 5; t += 0.001) if (Math.abs(1 - x(t)) > eps) last = t
  return Math.ceil(last * 100) / 100
}

function linearEasing(stiffness: number, dampingRatio: number) {
  const x = spring(stiffness, dampingRatio)
  const d = settleTime(x)
  const n = dampingRatio < 1 ? 48 : 24
  const pts = Array.from({ length: n + 1 }, (_, i) =>
    i === n ? 1 : +x((d * i) / n).toFixed(4)
  )
  return { easing: `linear(${pts.join(", ")})`, duration: Math.round(d * 1000) }
}

/** M3 motion scheme tokens (Compose MotionScheme / m3.material.io) */
const SCHEMES = {
  expressive: {
    "fast-spatial": [800, 0.6],
    "default-spatial": [380, 0.8],
    "slow-spatial": [200, 0.8],
    "fast-effects": [3800, 1],
    "default-effects": [1600, 1],
    "slow-effects": [800, 1],
  },
  standard: {
    "fast-spatial": [1400, 0.9],
    "default-spatial": [700, 0.9],
    "slow-spatial": [300, 0.9],
    "fast-effects": [3800, 1],
    "default-effects": [1600, 1],
    "slow-effects": [800, 1],
  },
} as const

function springCss(scheme: keyof typeof SCHEMES, indent: string) {
  return Object.entries(SCHEMES[scheme])
    .map(([name, [k, z]]) => {
      const { easing, duration } = linearEasing(k, z)
      return [
        `${indent}--md-sys-motion-spring-${name}: ${easing};`,
        `${indent}--md-sys-motion-spring-${name}-duration: ${duration}ms;`,
      ].join("\n")
    })
    .join("\n")
}

/* ---------- output ---------- */

const css = `/* Generated by scripts/gen-tokens.ts — do not edit by hand. */

/* Default color scheme: the official M3 Expressive baseline */
${themeCss({ source: { primary: "#6750A4" }, variant: "baseline" })}
/* Motion springs: expressive is the default scheme */
:root,
[data-motion="expressive"] {
${springCss("expressive", "  ")}
}

[data-motion="standard"] {
${springCss("standard", "  ")}
}
`

writeFileSync(OUT, css)
console.log(`wrote ${OUT}`)
