/**
 * The M3 Expressive baseline color scheme, taken from Google's Compose
 * Material3 tokens (ColorLightTokens / ColorDarkTokens / PaletteTokens) with
 * the expressive changes of `expressiveLightColorScheme()`: in light mode the
 * on-*-container roles use tone 30 instead of tone 10.
 *
 * `*-dim` roles only exist in the 2025 spec; here they equal the base role.
 */
export const BASELINE = {
  light: {
    background: "#FEF7FF",
    error: "#B3261E",
    "error-container": "#F9DEDC",
    "error-dim": "#B3261E",
    "inverse-on-surface": "#F5EFF7",
    "inverse-primary": "#D0BCFF",
    "inverse-surface": "#322F35",
    "on-background": "#1D1B20",
    "on-error": "#FFFFFF",
    "on-error-container": "#8C1D18",
    "on-primary": "#FFFFFF",
    "on-primary-container": "#4F378B",
    "on-primary-fixed": "#21005D",
    "on-primary-fixed-variant": "#4F378B",
    "on-secondary": "#FFFFFF",
    "on-secondary-container": "#4A4458",
    "on-secondary-fixed": "#1D192B",
    "on-secondary-fixed-variant": "#4A4458",
    "on-surface": "#1D1B20",
    "on-surface-variant": "#49454F",
    "on-tertiary": "#FFFFFF",
    "on-tertiary-container": "#633B48",
    "on-tertiary-fixed": "#31111D",
    "on-tertiary-fixed-variant": "#633B48",
    outline: "#79747E",
    "outline-variant": "#CAC4D0",
    primary: "#6750A4",
    "primary-container": "#EADDFF",
    "primary-dim": "#6750A4",
    "primary-fixed": "#EADDFF",
    "primary-fixed-dim": "#D0BCFF",
    scrim: "#000000",
    secondary: "#625B71",
    "secondary-container": "#E8DEF8",
    "secondary-dim": "#625B71",
    "secondary-fixed": "#E8DEF8",
    "secondary-fixed-dim": "#CCC2DC",
    shadow: "#000000",
    surface: "#FEF7FF",
    "surface-bright": "#FEF7FF",
    "surface-container": "#F3EDF7",
    "surface-container-high": "#ECE6F0",
    "surface-container-highest": "#E6E0E9",
    "surface-container-low": "#F7F2FA",
    "surface-container-lowest": "#FFFFFF",
    "surface-dim": "#DED8E1",
    "surface-tint": "#6750A4",
    "surface-variant": "#E7E0EC",
    tertiary: "#7D5260",
    "tertiary-container": "#FFD8E4",
    "tertiary-dim": "#7D5260",
    "tertiary-fixed": "#FFD8E4",
    "tertiary-fixed-dim": "#EFB8C8",
  },
  dark: {
    background: "#141218",
    error: "#F2B8B5",
    "error-container": "#8C1D18",
    "error-dim": "#F2B8B5",
    "inverse-on-surface": "#322F35",
    "inverse-primary": "#6750A4",
    "inverse-surface": "#E6E0E9",
    "on-background": "#E6E0E9",
    "on-error": "#601410",
    "on-error-container": "#F9DEDC",
    "on-primary": "#381E72",
    "on-primary-container": "#EADDFF",
    "on-primary-fixed": "#21005D",
    "on-primary-fixed-variant": "#4F378B",
    "on-secondary": "#332D41",
    "on-secondary-container": "#E8DEF8",
    "on-secondary-fixed": "#1D192B",
    "on-secondary-fixed-variant": "#4A4458",
    "on-surface": "#E6E0E9",
    "on-surface-variant": "#CAC4D0",
    "on-tertiary": "#492532",
    "on-tertiary-container": "#FFD8E4",
    "on-tertiary-fixed": "#31111D",
    "on-tertiary-fixed-variant": "#633B48",
    outline: "#938F99",
    "outline-variant": "#49454F",
    primary: "#D0BCFF",
    "primary-container": "#4F378B",
    "primary-dim": "#D0BCFF",
    "primary-fixed": "#EADDFF",
    "primary-fixed-dim": "#D0BCFF",
    scrim: "#000000",
    secondary: "#CCC2DC",
    "secondary-container": "#4A4458",
    "secondary-dim": "#CCC2DC",
    "secondary-fixed": "#E8DEF8",
    "secondary-fixed-dim": "#CCC2DC",
    shadow: "#000000",
    surface: "#141218",
    "surface-bright": "#3B383E",
    "surface-container": "#211F26",
    "surface-container-high": "#2B2930",
    "surface-container-highest": "#36343B",
    "surface-container-low": "#1D1B20",
    "surface-container-lowest": "#0F0D13",
    "surface-dim": "#141218",
    "surface-tint": "#D0BCFF",
    "surface-variant": "#49454F",
    tertiary: "#EFB8C8",
    "tertiary-container": "#633B48",
    "tertiary-dim": "#EFB8C8",
    "tertiary-fixed": "#FFD8E4",
    "tertiary-fixed-dim": "#EFB8C8",
  },
} as const
